spring:
  datasource:
    url: jdbc:mysql://39.97.234.52:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8080

#logging.file.name=1.log  # 默认是spring.log
logging:
  file:
    path: logs
